const types = require('./types');
const relations = require('./relationships');


function outputCssSelectors () {
	console.log('// Generated by generate_relationships.js\n');

	relations.getAllRelations().forEach(relationName => {
		const selectors = [];

		Object.keys(types).forEach((meAbbr) => {
			Object.keys(types).forEach((youAbbr) => {
				// For the view, we mark relationships for "me", but from "you" perspective.
				// That is, if we mark all relationships for type A,
				// 	and A is supervisee in A-B relationship, we mark B as supervisor (from their perspective).
				if (relationName === relations.getRelationForYou(types[meAbbr].dichotomyAbbr, types[youAbbr].dichotomyAbbr)) {
					selectors.push(`.rel-for-${meAbbr} .type-${youAbbr}`);
				}
			});
		});

		console.log(selectors.join(',\n') + ' {\n\t.rel-' + relationName + ' {\n\t\tdisplay: block;\n\t}\n}\n');
	});
}

outputCssSelectors();
