
module.exports = {
//export default { Does not work in Node.
	EIE: {
		epithet: 'Hamlet',
		socionicsAbbr: 'EIE',
		dichotomyAbbr: 'ENFj',
		socialRole: 'skolotājs',
		quadra: 'β',
		functions: ['Fe', 'Ni', 'Te', 'Si', 'Ti', 'Se', 'Fi', 'Ne'],
		professionalClub: 'humanitarians',
		communicationStyle: 'passionate',
		dichotomies: {
			aristocraticNotDemocratic: true,
			askingNotDeclaring: true,
			carefreeNotFarsighted: true,
			constructivistNotEmotivist: true,
			judiciousNotDecisive: false,
			positiveNotNegative: false,
			processNotResult: true,
			staticNotDynamic: false,
			subjectiveNotObjective: true,
			tacticalNotStrategic: false,
			yieldingNotObstinate: false
		}
	},
	EII: {
		epithet: 'Dostoyevsky',
		socionicsAbbr: 'EII',
		dichotomyAbbr: 'INFj',
		socialRole: 'humānists',
		quadra: 'δ',
		functions: ['Fi', 'Ne', 'Ti', 'Se', 'Te', 'Si', 'Fe', 'Ni'],
		professionalClub: 'humanitarians',
		communicationStyle: 'sincere',
		dichotomies: {
			aristocraticNotDemocratic: true,
			askingNotDeclaring: false,
			carefreeNotFarsighted: false,
			constructivistNotEmotivist: true,
			judiciousNotDecisive: true,
			positiveNotNegative: true,
			processNotResult: true,
			staticNotDynamic: true,
			subjectiveNotObjective: false,
			tacticalNotStrategic: false,
			yieldingNotObstinate: true
		}
	},
	ESE: {
		epithet: 'Hugo',
		socionicsAbbr: 'ESE',
		dichotomyAbbr: 'ESFj',
		socialRole: 'iedvesmotājs',
		quadra: 'α',
		functions: ['Fe', 'Si', 'Te', 'Ni', 'Ti', 'Ne', 'Fi', 'Se'],
		professionalClub: 'socials',
		communicationStyle: 'passionate',
		dichotomies: {
			aristocraticNotDemocratic: false,
			askingNotDeclaring: false,
			carefreeNotFarsighted: false,
			constructivistNotEmotivist: true,
			judiciousNotDecisive: true,
			positiveNotNegative: true,
			processNotResult: false,
			staticNotDynamic: false,
			subjectiveNotObjective: true,
			tacticalNotStrategic: true,
			yieldingNotObstinate: false
		}
	},
	ESI: {
		epithet: 'Dreiser',
		socionicsAbbr: 'ESI',
		dichotomyAbbr: 'ISFj',
		socialRole: 'sargātājs',
		quadra: 'γ',
		functions: ['Fi', 'Se', 'Ti', 'Ne', 'Te', 'Ni', 'Fe', 'Si'],
		professionalClub: 'socials',
		communicationStyle: 'sincere',
		dichotomies: {
			aristocraticNotDemocratic: false,
			askingNotDeclaring: true,
			carefreeNotFarsighted: true,
			constructivistNotEmotivist: true,
			judiciousNotDecisive: false,
			positiveNotNegative: false,
			processNotResult: false,
			staticNotDynamic: true,
			subjectiveNotObjective: false,
			tacticalNotStrategic: true,
			yieldingNotObstinate: true
		}
	},
	ILE: {
		epithet: 'Don Quixote',
		socionicsAbbr: 'ILE',
		dichotomyAbbr: 'ENTp',
		socialRole: 'meklētājs',
		quadra: 'α',
		functions: ['Ne', 'Ti', 'Se', 'Fi', 'Si', 'Fe', 'Ni', 'Te'],
		professionalClub: 'researchers',
		communicationStyle: 'businesslike',
		dichotomies: {
			aristocraticNotDemocratic: false,
			askingNotDeclaring: true,
			carefreeNotFarsighted: true,
			constructivistNotEmotivist: true,
			judiciousNotDecisive: true,
			positiveNotNegative: true,
			processNotResult: true,
			staticNotDynamic: true,
			subjectiveNotObjective: true,
			tacticalNotStrategic: true,
			yieldingNotObstinate: true
		}
	},
	ILI: {
		epithet: 'Balzac',
		socionicsAbbr: 'ILI',
		dichotomyAbbr: 'INTp',
		socialRole: 'kritiķis',
		quadra: 'γ',
		functions: ['Ni', 'Te', 'Si', 'Fe', 'Se', 'Fi', 'Ne', 'Ti'],
		professionalClub: 'researchers',
		communicationStyle: 'coldblooded',
		dichotomies: {
			aristocraticNotDemocratic: false,
			askingNotDeclaring: false,
			carefreeNotFarsighted: false,
			constructivistNotEmotivist: true,
			judiciousNotDecisive: false,
			positiveNotNegative: false,
			processNotResult: true,
			staticNotDynamic: false,
			subjectiveNotObjective: false,
			tacticalNotStrategic: true,
			yieldingNotObstinate: false
		}
	},
	IEE: {
		epithet: 'Huxley',
		socionicsAbbr: 'IEE',
		dichotomyAbbr: 'ENFp',
		socialRole: 'komunikators',
		quadra: 'δ',
		functions: ['Ne', 'Fi', 'Se', 'Ti', 'Si', 'Te', 'Ni', 'Fe'],
		professionalClub: 'humanitarians',
		communicationStyle: 'passionate',
		dichotomies: {
			aristocraticNotDemocratic: true,
			askingNotDeclaring: false,
			carefreeNotFarsighted: true,
			constructivistNotEmotivist: false,
			judiciousNotDecisive: true,
			positiveNotNegative: false,
			processNotResult: false,
			staticNotDynamic: true,
			subjectiveNotObjective: false,
			tacticalNotStrategic: true,
			yieldingNotObstinate: false
		}
	},
	IEI: {
		epithet: 'Yesenin',
		socionicsAbbr: 'IEI',
		dichotomyAbbr: 'INFp',
		socialRole: 'motivētājs',
		quadra: 'β',
		functions: ['Ni', 'Fe', 'Si', 'Te', 'Se', 'Ti', 'Ne', 'Fi'],
		professionalClub: 'humanitarians',
		communicationStyle: 'sincere',
		dichotomies: {
			aristocraticNotDemocratic: true,
			askingNotDeclaring: true,
			carefreeNotFarsighted: false,
			constructivistNotEmotivist: false,
			judiciousNotDecisive: false,
			positiveNotNegative: true,
			processNotResult: false,
			staticNotDynamic: false,
			subjectiveNotObjective: true,
			tacticalNotStrategic: true,
			yieldingNotObstinate: true
		}
	},
	LIE: {
		epithet: 'Jack London',
		socionicsAbbr: 'LIE',
		dichotomyAbbr: 'ENTj',
		socialRole: 'uzņēmējs',
		quadra: 'γ',
		functions: ['Te', 'Ni', 'Fe', 'Si', 'Fi', 'Se', 'Ti', 'Ne'],
		professionalClub: 'researchers',
		communicationStyle: 'businesslike',
		dichotomies: {
			aristocraticNotDemocratic: false,
			askingNotDeclaring: false,
			carefreeNotFarsighted: true,
			constructivistNotEmotivist: false,
			judiciousNotDecisive: false,
			positiveNotNegative: true,
			processNotResult: false,
			staticNotDynamic: false,
			subjectiveNotObjective: false,
			tacticalNotStrategic: false,
			yieldingNotObstinate: true
		}
	},
	LII: {
		epithet: 'Robespierre',
		socionicsAbbr: 'LII',
		dichotomyAbbr: 'INTj',
		socialRole: 'analītiķis',
		quadra: 'α',
		functions: ['Ti', 'Ne', 'Fi', 'Se', 'Fe', 'Si', 'Te', 'Ni'],
		professionalClub: 'researchers',
		communicationStyle: 'coldblooded',
		dichotomies: {
			aristocraticNotDemocratic: false,
			askingNotDeclaring: true,
			carefreeNotFarsighted: false,
			constructivistNotEmotivist: false,
			judiciousNotDecisive: true,
			positiveNotNegative: false,
			processNotResult: false,
			staticNotDynamic: true,
			subjectiveNotObjective: true,
			tacticalNotStrategic: false,
			yieldingNotObstinate: false
		}
	},
	LSE: {
		epithet: 'Stierlitz',
		socionicsAbbr: 'LSE',
		dichotomyAbbr: 'ESTj',
		socialRole: 'administrētājs',
		quadra: 'δ',
		functions: ['Te', 'Si', 'Fe', 'Ni', 'Fi', 'Ne', 'Ti', 'Se'],
		professionalClub: 'pragmatists',
		communicationStyle: 'businesslike',
		dichotomies: {
			aristocraticNotDemocratic: true,
			askingNotDeclaring: true,
			carefreeNotFarsighted: false,
			constructivistNotEmotivist: false,
			judiciousNotDecisive: true,
			positiveNotNegative: false,
			processNotResult: true,
			staticNotDynamic: false,
			subjectiveNotObjective: false,
			tacticalNotStrategic: true,
			yieldingNotObstinate: true
		}
	},
	LSI: {
		epithet: 'Maxim Gorky',
		socionicsAbbr: 'LSI',
		dichotomyAbbr: 'ISTj',
		socialRole: 'sistematizētājs',
		quadra: 'β',
		functions: ['Ti', 'Se', 'Fi', 'Ne', 'Fe', 'Ni', 'Te', 'Si'],
		professionalClub: 'pragmatists',
		communicationStyle: 'coldblooded',
		dichotomies: {
			aristocraticNotDemocratic: true,
			askingNotDeclaring: false,
			carefreeNotFarsighted: true,
			constructivistNotEmotivist: false,
			judiciousNotDecisive: false,
			positiveNotNegative: true,
			processNotResult: true,
			staticNotDynamic: true,
			subjectiveNotObjective: true,
			tacticalNotStrategic: true,
			yieldingNotObstinate: false
		}
	},
	SLE: {
		epithet: 'Zhukov',
		socionicsAbbr: 'SLE',
		dichotomyAbbr: 'ESTp',
		socialRole: 'rīkotājs',
		quadra: 'β',
		functions: ['Se', 'Ti', 'Ne', 'Fi', 'Ni', 'Fe', 'Si', 'Te'],
		professionalClub: 'pragmatists',
		communicationStyle: 'businesslike',
		dichotomies: {
			aristocraticNotDemocratic: true,
			askingNotDeclaring: false,
			carefreeNotFarsighted: false,
			constructivistNotEmotivist: true,
			judiciousNotDecisive: false,
			positiveNotNegative: false,
			processNotResult: false,
			staticNotDynamic: true,
			subjectiveNotObjective: true,
			tacticalNotStrategic: false,
			yieldingNotObstinate: true
		}
	},
	SLI: {
		epithet: 'Gabin',
		socionicsAbbr: 'SLI',
		dichotomyAbbr: 'ISTp',
		socialRole: 'amatnieks',
		quadra: 'δ',
		functions: ['Si', 'Te', 'Ni', 'Fe', 'Ne', 'Fi', 'Se', 'Ti'],
		professionalClub: 'pragmatists',
		communicationStyle: 'coldblooded',
		dichotomies: {
			aristocraticNotDemocratic: true,
			askingNotDeclaring: true,
			carefreeNotFarsighted: true,
			constructivistNotEmotivist: true,
			judiciousNotDecisive: true,
			positiveNotNegative: true,
			processNotResult: false,
			staticNotDynamic: false,
			subjectiveNotObjective: false,
			tacticalNotStrategic: false,
			yieldingNotObstinate: false
		}
	},
	SEE: {
		epithet: 'Napoleon',
		socionicsAbbr: 'SEE',
		dichotomyAbbr: 'ESFp',
		socialRole: 'politiķis',
		quadra: 'γ',
		functions: ['Se', 'Fi', 'Ne', 'Ti', 'Ni', 'Te', 'Si', 'Fe'],
		professionalClub: 'socials',
		communicationStyle: 'passionate',
		dichotomies: {
			aristocraticNotDemocratic: false,
			askingNotDeclaring: true,
			carefreeNotFarsighted: false,
			constructivistNotEmotivist: false,
			judiciousNotDecisive: false,
			positiveNotNegative: true,
			processNotResult: true,
			staticNotDynamic: true,
			subjectiveNotObjective: false,
			tacticalNotStrategic: false,
			yieldingNotObstinate: false
		}
	},
	SEI: {
		epithet: 'Dumas',
		socionicsAbbr: 'SEI',
		dichotomyAbbr: 'ISFp',
		socialRole: 'starpnieks',
		quadra: 'α',
		functions: ['Si', 'Fe', 'Ni', 'Te', 'Ne', 'Ti', 'Se', 'Fi'],
		professionalClub: 'socials',
		communicationStyle: 'sincere',
		dichotomies: {
			aristocraticNotDemocratic: false,
			askingNotDeclaring: false,
			carefreeNotFarsighted: true,
			constructivistNotEmotivist: false,
			judiciousNotDecisive: true,
			positiveNotNegative: false,
			processNotResult: true,
			staticNotDynamic: false,
			subjectiveNotObjective: true,
			tacticalNotStrategic: false,
			yieldingNotObstinate: true
		}
	}
};
